# Buggle Configuration
#
# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0

# Global settings. These are for testing; to get anything done you need to
# change dry-run to @c false.
verbose = false
dry-run = true

# The queries all have a name, a kind (owner or product) and a string to match.
# These are translated into bugzilla queries for the to-be-matched owner
# or product. The name is used for display purposes.

[[queries]]
name = "me"
kind = "owner"
match = "adridg@FreeBSD.org"

[[queries]]
name = "cmake"
kind = "product"
match = "cmake"

[[queries]]
name = "desktop"
kind = "owner"
match = "desktop@FreeBSD.org"

[[queries]]
name = "kde"
kind = "owner"
match = "kde@FreeBSD.org"

# Authentication for social-media-posts. The keys are documented here,
# but you really **really** should put them in buggle-auth.toml, which
# is ignored in this repository and overrides the values here.

# This is the application key and secret; obtained from the developer portal.
[twitter-app]
key = "application-key"
secret = "application-secret"

# This is the user key and secret for the logged-in user.
[twitter-user]
key = "user-key"
secret = "user-secret"
